Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "mhassaniS" do |control|
    control.vm.hostname = "mhassaniS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "mhassaniS"]
      v.memory = 1024
      v.cpus = 1
    end
    control.vm.provision "shell", path: "scripts/server.sh"
  end

end