Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  # server role is to create the cluster and manage it, while the worker role is to run the workloads assigned by the server.
  config.vm.define "mhassaniS" do |control| # Define the first VM as the control/server node.
    control.vm.hostname = "mhassaniS" # This sets the internal identity of the computer.
    control.vm.network "private_network", ip: "192.168.56.110" # Give it a static host-only IP for node-to-node access.
    control.vm.provider "virtualbox" do |v| # Apply VirtualBox-only settings to this VM.
      v.customize ["modifyvm", :id, "--name", "mhassaniS"] # VirtualBox Appearance: Rename the VM in the VirtualBox UI and CLI for easier identification.
      v.memory = 1024
      v.cpus = 1
    end
    control.vm.provision "shell", path: "scripts/server.sh" # Run the server setup script during `vagrant up`.
  end

  config.vm.define "mhassaniSW" do |worker| # Define the second VM as the worker/agent node.
    worker.vm.hostname = "mhassaniSW"
    worker.vm.network "private_network", ip: "192.168.56.111" # Give it a different static IP on the same private network.
    worker.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "mhassaniSW"]
      v.memory = 512
      v.cpus = 1
    end
    worker.vm.provision "shell", path: "scripts/agent.sh" # Run the worker setup script during `vagrant up`.
  end

end