Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04" # Use the latest Ubuntu 24.04 box from Vagrant Cloud

  config.vm.define "mhassaniS" do |server|
    server.vm.hostname = "mhassaniS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "mhassaniS"]
      v.memory = 2048
      v.cpus = 2
    end
    server.vm.provision "shell", path: "scripts/server.sh"
  end

  config.vm.define "mhassaniSW" do |worker|
    worker.vm.hostname = "mhassaniSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "mhassaniSW"]
      v.memory = 2048
      v.cpus = 2
    end
    worker.vm.provision "shell", path: "scripts/agent.sh"
  end
end
